# Generated by Django 4.1.7 on 2023-03-13 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_book_publisher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='age',
            new_name='Edad',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publisher',
            new_name='Editorial',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='publication_date',
            new_name='Fecha_Publicacion',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='Titulo',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='city',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='address',
            new_name='Direccion',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='country',
            new_name='Estado_o_Provincia',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='name',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='state_province',
            new_name='Pais',
        ),
        migrations.RenameField(
            model_name='publisher',
            old_name='website',
            new_name='Website',
        ),
    ]
