# Generated by Django 4.1.7 on 2023-03-13 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_age_author_edad_rename_name_author_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Fecha_Publicacion',
            new_name='publication_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Editorial',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Titulo',
            new_name='title',
        ),
    ]
