# Generated by Django 4.1.7 on 2023-03-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_nombre_author_name_rename_autor_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Edad',
            new_name='age',
        ),
    ]
